[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Primagon/CSc44800_Assignment_03/blob/main/CSc44800_Assignment3.ipynb)

## Part 1. Loading the dataset

In [39]:
# Using pandas load the dataset (load remotely, not locally)
# Output the first 15 rows of the data
# Display a summary of the table information (number of datapoints, etc.)
import numpy as np
import pandas as pd

slime = pd.read_csv("https://raw.githubusercontent.com/profmcnich/example_notebook/main/science_data_large.csv")
slime.head(15)

Temperature °C  Mols KCL     Size nm^3
0              469       647  6.244743e+05
1              403       694  5.779610e+05
2              302       975  6.196847e+05
3              779       916  1.460449e+06
4              901        18  4.325726e+04
5              545       637  7.124634e+05
6              660       519  7.006960e+05
7              143       869  2.718260e+05
8               89       461  8.919803e+04
9              294       776  4.770210e+05
10             991       117  2.441771e+05
11             307       781  5.006455e+05
12             206        70  3.145200e+04
13             437       599  5.390215e+05
14             566        75  9.185271e+04

In [40]:
slime

Temperature °C  Mols KCL     Size nm^3
0               469       647  6.244743e+05
1               403       694  5.779610e+05
2               302       975  6.196847e+05
3               779       916  1.460449e+06
4               901        18  4.325726e+04
..              ...       ...           ...
995             894       847  1.545661e+06
996             327       982  6.737041e+05
997             791       213  3.477543e+05
998             769       553  8.684794e+05
999             919       452  8.476413e+05

[1000 rows x 3 columns]

In [41]:
slime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Temperature °C  1000 non-null   int64  
 1   Mols KCL        1000 non-null   int64  
 2   Size nm^3       1000 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 23.6 KB


## Part 2. Splitting the dataset

In [42]:
# Take the pandas dataset and split it into our features (X) and label (y)

# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)

features = slime[["Temperature °C", "Mols KCL"]]
features

Temperature °C  Mols KCL
0               469       647
1               403       694
2               302       975
3               779       916
4               901        18
..              ...       ...
995             894       847
996             327       982
997             791       213
998             769       553
999             919       452

[1000 rows x 2 columns]

In [43]:
label = slime[['Size nm^3']]
label

Size nm^3
0    6.244743e+05
1    5.779610e+05
2    6.196847e+05
3    1.460449e+06
4    4.325726e+04
..            ...
995  1.545661e+06
996  6.737041e+05
997  3.477543e+05
998  8.684794e+05
999  8.476413e+05

[1000 rows x 1 columns]

In [44]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, label, test_size = 0.1)

## Part 3. Perform a Linear Regression

In [45]:
# Use sklearn to train a model on the training set

# Create a sample datapoint and predict the output of that sample with the trained model

# Report on the score for that model, in your own words (markdown, not code) explain what the score means

# Extract the coefficents and intercept from the model and write an equation for your h(x) using LaTeX
from sklearn.linear_model import LinearRegression

reg = LinearRegression().fit(X_train, y_train)
reg.predict(X_test)

array([[1062691.21777251],
       [ 937924.84806223],
       [ 335145.06334462],
       [ 647607.29933025],
       [ 295245.86826049],
       [-208422.53539193],
       [ 577269.42299283],
       [ 743810.4513314 ],
       [ 549431.6458775 ],
       [ 989530.30324702],
       [ 912562.87894221],
       [1011661.50455618],
       [ 638763.8937211 ],
       [1054766.77600525],
       [1116877.62446192],
       [ 252862.84854242],
       [ 165936.34267567],
       [1213686.76814655],
       [ 329793.64540659],
       [ 471896.40727963],
       [1346588.59713599],
       [ 116865.64496646],
       [ 776622.16647699],
       [   4272.94495318],
       [   8671.96047149],
       [ 130725.99377211],
       [ 166844.18997936],
       [ 354626.0665872 ],
       [1287432.99122891],
       [-230565.6726958 ],
       [ 829210.36275976],
       [1277722.37407601],
       [ 739031.58649902],
       [1000519.05042927],
       [ 565497.92464953],
       [ 710868.08177406],
       [  69810.45387511],
 

In [46]:
y_test['Size nm^3']

322    1.231433e+06
156    9.799923e+05
858    2.388269e+05
750    4.492695e+05
855    2.691125e+05
           ...     
887    4.542493e+05
657    1.084296e+05
985    1.968257e+03
549    7.614640e+04
950    4.812353e+05
Name: Size nm^3, Length: 100, dtype: float64

In [47]:
reg.score(X_test, y_test)

0.8486260122250803

With a score of 0.85, my models predicates roughly around 85% correct.   

In [48]:
reg.coef_

array([[ 873.58926935, 1036.04334591]])

In [49]:
reg.intercept_

array([-415511.75566436])

$h(892.49515243) = 1036.04334591 = 873.58926935m - 415511.75566436\\
m = 476.82\\
h(x) = 476.82x - 415511.75566436$

## Part 4. Use Cross Validation

In [50]:
# Use the cross_val_score function to repeat your experiment across many shuffles of the data

# Report on their finding and their significance
from sklearn.model_selection import cross_val_score

cross_val_score(LinearRegression(), X_train, y_train, cv=3)

C:\Users\kenne\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:442: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  fold_sizes = np.full(n_splits, n_samples // n_splits, dtype=np.int)
C:\Users\kenne\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:102: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; f

array([0.86454692, 0.85788336, 0.86152388])

When doing cross_val_score with 3-folds, it has returned an average of 0.86132 and a standard deviation of 0.002724.
Cross-validating shows that it can increase the accuracy of the model.

## Part 5. Using Polynomial Regression

In [103]:
# Using the PolynomialFeatures library perform another regression on an augmented dataset of degree 2

# Report on the metrics and output the resultant equation as you did in Part 3.
from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model

poly = PolynomialFeatures(2)
poly.fit_transform(X_train)

array([[1.00000e+00, 3.89000e+02, 5.70000e+02, 1.51321e+05, 2.21730e+05,
        3.24900e+05],
       [1.00000e+00, 9.54000e+02, 8.55000e+02, 9.10116e+05, 8.15670e+05,
        7.31025e+05],
       [1.00000e+00, 8.36000e+02, 5.73000e+02, 6.98896e+05, 4.79028e+05,
        3.28329e+05],
       ...,
       [1.00000e+00, 4.15000e+02, 4.60000e+01, 1.72225e+05, 1.90900e+04,
        2.11600e+03],
       [1.00000e+00, 1.61000e+02, 6.22000e+02, 2.59210e+04, 1.00142e+05,
        3.86884e+05],
       [1.00000e+00, 8.83000e+02, 8.52000e+02, 7.79689e+05, 7.52316e+05,
        7.25904e+05]])

In [104]:
# to fix the warning of using BaynesianRidge(), I had to change I from a Pandas DataFrame to an 1d Array. It worked
# regardless but this is a just incase.
label = slime['Size nm^3']
label

0      6.244743e+05
1      5.779610e+05
2      6.196847e+05
3      1.460449e+06
4      4.325726e+04
           ...     
995    1.545661e+06
996    6.737041e+05
997    3.477543e+05
998    8.684794e+05
999    8.476413e+05
Name: Size nm^3, Length: 1000, dtype: float64

In [105]:
poly_reg = PolynomialFeatures(degree = 2)
X_poly = poly_reg.fit_transform(features)
pol_reg = linear_model.BayesianRidge()
pol_reg.fit(X_poly, label)

BayesianRidge(alpha_1=1e-06, alpha_2=1e-06, compute_score=False, copy_X=True,
              fit_intercept=True, lambda_1=1e-06, lambda_2=1e-06, n_iter=300,
              normalize=False, tol=0.001, verbose=False)

In [106]:
pol_reg.predict(X_poly)

array([6.24474257e+05, 5.77961029e+05, 6.19684714e+05, 1.46044903e+06,
       4.32572572e+04, 7.12463400e+05, 7.00696029e+05, 2.71826029e+05,
       8.91980286e+04, 4.77021029e+05, 2.44177114e+05, 5.00645457e+05,
       3.14520000e+04, 5.39021457e+05, 9.18527143e+04, 3.95288286e+04,
       5.38421457e+05, 1.14843143e+04, 1.48585029e+05, 4.16308457e+05,
       1.31596457e+05, 4.82433257e+05, 1.16136540e+06, 1.36031143e+04,
       4.24489114e+05, 1.97787143e+04, 8.03035857e+05, 3.21295000e+05,
       6.95233029e+05, 2.23961400e+05, 1.10432926e+06, 1.92627283e+06,
       5.21373600e+05, 7.91715314e+05, 4.53954314e+05, 5.11930286e+04,
       5.94753143e+04, 4.40629714e+05, 4.60782857e+05, 7.88616000e+04,
       8.03208600e+05, 2.28364457e+05, 2.41597829e+05, 1.04578046e+06,
       6.59932571e+04, 6.18540286e+04, 3.97636457e+05, 4.93009714e+05,
       1.18457029e+05, 2.42666829e+05, 1.26718971e+06, 1.28496257e+05,
       6.10293600e+05, 5.76091143e+04, 9.13729029e+05, 1.41796260e+06,
      

In [107]:
pol_reg.score(X_poly, label)

1.0

With a score of 1.0, it shows that using Lasso and PolynomialFeatures would have my model predict roughly 100% correct. Which is a huge imporvement over the score from linear regression which was 0.85

In [108]:
pol_reg.coef_

array([ 0.00000000e+00,  1.20000000e+01, -1.22330675e-07, -7.19779791e-12,
        2.00000000e+00,  2.85714287e-02])

In [109]:
pol_reg.intercept_

1.7097219824790955e-05

In [110]:
reg_label = "Inliers coef:%s - b:%0.2f" % \
            (np.array2string(pol_reg.coef_,
                             formatter={'float_kind': lambda fk: "%.3f" % fk}),
            pol_reg.intercept_)
print(reg_label)

Inliers coef:[0.000 12.000 -0.000 -0.000 2.000 0.029] - b:0.00


$y = 0 + 12a - 0b - 0a^2 + 2ab + 0.029b^2 - 0\\ $