[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Primagon/CSc44800_Assignment_03/blob/main/CSc44800_Assignment3.ipynb)

## Part 1. Loading the dataset

In [39]:
# Using pandas load the dataset (load remotely, not locally)
# Output the first 15 rows of the data
# Display a summary of the table information (number of datapoints, etc.)
import numpy as np
import pandas as pd

slime = pd.read_csv("https://raw.githubusercontent.com/profmcnich/example_notebook/main/science_data_large.csv")
slime.head(15)

Temperature °C  Mols KCL     Size nm^3
0              469       647  6.244743e+05
1              403       694  5.779610e+05
2              302       975  6.196847e+05
3              779       916  1.460449e+06
4              901        18  4.325726e+04
5              545       637  7.124634e+05
6              660       519  7.006960e+05
7              143       869  2.718260e+05
8               89       461  8.919803e+04
9              294       776  4.770210e+05
10             991       117  2.441771e+05
11             307       781  5.006455e+05
12             206        70  3.145200e+04
13             437       599  5.390215e+05
14             566        75  9.185271e+04

In [40]:
slime

Temperature °C  Mols KCL     Size nm^3
0               469       647  6.244743e+05
1               403       694  5.779610e+05
2               302       975  6.196847e+05
3               779       916  1.460449e+06
4               901        18  4.325726e+04
..              ...       ...           ...
995             894       847  1.545661e+06
996             327       982  6.737041e+05
997             791       213  3.477543e+05
998             769       553  8.684794e+05
999             919       452  8.476413e+05

[1000 rows x 3 columns]

In [41]:
slime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Temperature °C  1000 non-null   int64  
 1   Mols KCL        1000 non-null   int64  
 2   Size nm^3       1000 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 23.6 KB


## Part 2. Splitting the dataset

In [42]:
# Take the pandas dataset and split it into our features (X) and label (y)

# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)

features = slime[["Temperature °C", "Mols KCL"]]
features

Temperature °C  Mols KCL
0               469       647
1               403       694
2               302       975
3               779       916
4               901        18
..              ...       ...
995             894       847
996             327       982
997             791       213
998             769       553
999             919       452

[1000 rows x 2 columns]

In [43]:
label = slime[['Size nm^3']]
label

Size nm^3
0    6.244743e+05
1    5.779610e+05
2    6.196847e+05
3    1.460449e+06
4    4.325726e+04
..            ...
995  1.545661e+06
996  6.737041e+05
997  3.477543e+05
998  8.684794e+05
999  8.476413e+05

[1000 rows x 1 columns]

In [44]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, label, test_size = 0.1)

## Part 3. Perform a Linear Regression

In [45]:
# Use sklearn to train a model on the training set

# Create a sample datapoint and predict the output of that sample with the trained model

# Report on the score for that model, in your own words (markdown, not code) explain what the score means

# Extract the coefficents and intercept from the model and write an equation for your h(x) using LaTeX
from sklearn.linear_model import LinearRegression

reg = LinearRegression().fit(X_train, y_train)
reg.predict(X_test)

array([[1062691.21777251],
       [ 937924.84806223],
       [ 335145.06334462],
       [ 647607.29933025],
       [ 295245.86826049],
       [-208422.53539193],
       [ 577269.42299283],
       [ 743810.4513314 ],
       [ 549431.6458775 ],
       [ 989530.30324702],
       [ 912562.87894221],
       [1011661.50455618],
       [ 638763.8937211 ],
       [1054766.77600525],
       [1116877.62446192],
       [ 252862.84854242],
       [ 165936.34267567],
       [1213686.76814655],
       [ 329793.64540659],
       [ 471896.40727963],
       [1346588.59713599],
       [ 116865.64496646],
       [ 776622.16647699],
       [   4272.94495318],
       [   8671.96047149],
       [ 130725.99377211],
       [ 166844.18997936],
       [ 354626.0665872 ],
       [1287432.99122891],
       [-230565.6726958 ],
       [ 829210.36275976],
       [1277722.37407601],
       [ 739031.58649902],
       [1000519.05042927],
       [ 565497.92464953],
       [ 710868.08177406],
       [  69810.45387511],
 

In [46]:
y_test['Size nm^3']

322    1.231433e+06
156    9.799923e+05
858    2.388269e+05
750    4.492695e+05
855    2.691125e+05
           ...     
887    4.542493e+05
657    1.084296e+05
985    1.968257e+03
549    7.614640e+04
950    4.812353e+05
Name: Size nm^3, Length: 100, dtype: float64

In [47]:
reg.score(X_test, y_test)

0.8486260122250803

With a score of 0.85, my models predicates roughly around 85% correct.   

In [48]:
reg.coef_

array([[ 873.58926935, 1036.04334591]])

In [49]:
reg.intercept_

array([-415511.75566436])

$h(892.49515243) = 1021.40888104 = 870.76520877m - 406308.82181339\\
m = 467.78\\
h(x) = 467.78x - 406308.82181339$

## Part 4. Use Cross Validation

In [50]:
# Use the cross_val_score function to repeat your experiment across many shuffles of the data

# Report on their finding and their significance
from sklearn.model_selection import cross_val_score

cross_val_score(LinearRegression(), X_train, y_train, cv=3)

C:\Users\kenne\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:442: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  fold_sizes = np.full(n_splits, n_samples // n_splits, dtype=np.int)
C:\Users\kenne\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:102: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; f

array([0.86454692, 0.85788336, 0.86152388])

When doing cross_val_score with 3-folds, it has returned an average of 0.85939 and a standard deviation of 0.00097921.
Cross-validating shows that it can increase the accuracy of the model.

## Part 5. Using Polynomial Regression

In [68]:
# Using the PolynomialFeatures library perform another regression on an augmented dataset of degree 2

# Report on the metrics and output the resultant equation as you did in Part 3.
from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model

poly = PolynomialFeatures(2)
poly.fit_transform(X_train)
# Ask the professor if he wants me to pass slime from the wording "augmented dataset" 
# or X_train only as stated in 1.1 Linear Models documentation

array([[1.00000e+00, 3.89000e+02, 5.70000e+02, 1.51321e+05, 2.21730e+05,
        3.24900e+05],
       [1.00000e+00, 9.54000e+02, 8.55000e+02, 9.10116e+05, 8.15670e+05,
        7.31025e+05],
       [1.00000e+00, 8.36000e+02, 5.73000e+02, 6.98896e+05, 4.79028e+05,
        3.28329e+05],
       ...,
       [1.00000e+00, 4.15000e+02, 4.60000e+01, 1.72225e+05, 1.90900e+04,
        2.11600e+03],
       [1.00000e+00, 1.61000e+02, 6.22000e+02, 2.59210e+04, 1.00142e+05,
        3.86884e+05],
       [1.00000e+00, 8.83000e+02, 8.52000e+02, 7.79689e+05, 7.52316e+05,
        7.25904e+05]])

In [69]:
poly_reg = PolynomialFeatures(degree = 2)
X_poly = poly_reg.fit_transform(features)
pol_reg = linear_model.Lasso()
pol_reg.fit(X_poly, label)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [70]:
pol_reg.predict(X_poly)

array([6.24472861e+05, 5.77959865e+05, 6.19685117e+05, 1.46044977e+06,
       4.32581521e+04, 7.12461966e+05, 7.00694621e+05, 2.71826870e+05,
       8.91988402e+04, 4.77020519e+05, 2.44178356e+05, 5.00644903e+05,
       3.14532190e+04, 5.39020025e+05, 9.18521588e+04, 3.95304059e+04,
       5.38420799e+05, 1.14869414e+04, 1.48585679e+05, 4.16308666e+05,
       1.31597213e+05, 4.82432057e+05, 1.16136525e+06, 1.36056202e+04,
       4.24488813e+05, 1.97796626e+04, 8.03034669e+05, 3.21294584e+05,
       6.95232434e+05, 2.23962008e+05, 1.10432873e+06, 1.92627575e+06,
       5.21372525e+05, 7.91713972e+05, 4.53953292e+05, 5.11926884e+04,
       5.94763853e+04, 4.40629458e+05, 4.60782315e+05, 7.88617539e+04,
       8.03209342e+05, 2.28364362e+05, 2.41598541e+05, 1.04577978e+06,
       6.59940915e+04, 6.18551695e+04, 3.97634917e+05, 4.93008199e+05,
       1.18456760e+05, 2.42666300e+05, 1.26719053e+06, 1.28495716e+05,
       6.10293654e+05, 5.76107658e+04, 9.13728401e+05, 1.41796392e+06,
      

In [71]:
pol_reg.score(X_poly, label)

0.9999999999928451

In [72]:
pol_reg.coef_

array([ 0.00000000e+00,  1.19856472e+01, -8.11370237e-03,  1.20296592e-05,
        2.00000303e+00,  2.85782704e-02])

In [73]:
pol_reg.intercept_

array([4.1559501])

In [74]:
reg_label = "Inliers coef:%s - b:%0.2f" % \
            (np.array2string(pol_reg.coef_,
                             formatter={'float_kind': lambda fk: "%.3f" % fk}),
            pol_reg.intercept_)
print(reg_label)

Inliers coef:[0.000 11.986 -0.008 0.000 2.000 0.029] - b:4.16


$y = 0 + 11.986a - 0.008b + 0a^2 + 2ab + 0.029b^2 - 4.16\\ $